import type { ExtensionRegistryEntry } from "./types.js";

export const CODE_REVIEWER_SKILL_URL =
  "https://github.com/vadimcomanescu/codex-skills/tree/main/skills/.curated/quality/code-reviewer";
export const FRONTEND_DESIGN_SKILL_URL =
  "https://github.com/vadimcomanescu/codex-skills/tree/main/skills/.curated/design/frontend-design";
export const SERENITY_INVEST_SKILL_URL = "https://github.com/leileqiTHU/serenity-invest-skill";

export const OFFICIAL_EXTENSION_REGISTRY_SCHEMA = "forge.extension-registry.v1";

export const BUILTIN_EXTENSION_REGISTRY: ExtensionRegistryEntry[] = [
  {
    id: "mcp-catalog:modelcontextprotocol-filesystem",
    kind: "mcp_server",
    name: "Filesystem",
    title: "Filesystem MCP",
    description: "Official MCP filesystem server for project-scoped file read/write workflows.",
    source: "modelcontextprotocol-filesystem",
    sourceLabel: "Forge built-in MCP catalog",
    trust: "official",
    version: "2026.1.14",
    capabilities: ["mcp.tool", "fs.read", "fs.write", "project"],
    risk: "caution",
    riskSummary: "Launches an official local MCP process and accesses only roots allowed by ForgeAgent sandbox.",
    installInput: { kind: "mcp_catalog", catalogId: "modelcontextprotocol-filesystem" },
    provenance: {
      type: "npm",
      packageName: "@modelcontextprotocol/server-filesystem",
      packageVersion: "2026.1.14",
      repository: "https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem",
    },
    tags: ["official", "filesystem", "workspace"],
    recommended: true,
  },
  {
    id: "mcp-catalog:modelcontextprotocol-everything",
    kind: "mcp_server",
    name: "Everything",
    title: "Everything MCP",
    description: "Official MCP reference server for testing tools, resources, prompts, sampling, and elicitation.",
    source: "modelcontextprotocol-everything",
    sourceLabel: "Forge built-in MCP catalog",
    trust: "official",
    version: "2026.1.26",
    capabilities: ["mcp.tool", "mcp.resource.read", "mcp.prompt.read", "mcp.sampling", "mcp.elicitation"],
    risk: "caution",
    riskSummary: "Reference server is useful for validation; sampling and elicitation still require Forge permissions.",
    installInput: { kind: "mcp_catalog", catalogId: "modelcontextprotocol-everything" },
    provenance: {
      type: "npm",
      packageName: "@modelcontextprotocol/server-everything",
      packageVersion: "2026.1.26",
      repository: "https://github.com/modelcontextprotocol/servers/tree/main/src/everything",
    },
    tags: ["official", "testing", "reference"],
    recommended: true,
  },
  {
    id: "mcp-catalog:modelcontextprotocol-memory",
    kind: "mcp_server",
    name: "Memory",
    title: "Memory MCP",
    description: "Official MCP memory server for local graph-style notes and relations.",
    source: "modelcontextprotocol-memory",
    sourceLabel: "Forge built-in MCP catalog",
    trust: "official",
    version: "2026.1.26",
    capabilities: ["mcp.tool", "memory.read", "memory.write"],
    risk: "caution",
    riskSummary: "Runs a local MCP process and can write memory data through normal Forge permissions.",
    installInput: { kind: "mcp_catalog", catalogId: "modelcontextprotocol-memory" },
    provenance: {
      type: "npm",
      packageName: "@modelcontextprotocol/server-memory",
      packageVersion: "2026.1.26",
      repository: "https://github.com/modelcontextprotocol/servers/tree/main/src/memory",
    },
    tags: ["official", "memory"],
    recommended: true,
  },
  {
    id: "mcp-catalog:modelcontextprotocol-sequential-thinking",
    kind: "mcp_server",
    name: "Sequential Thinking",
    title: "Sequential Thinking MCP",
    description: "Official MCP server for explicit step-by-step reasoning traces.",
    source: "modelcontextprotocol-sequential-thinking",
    sourceLabel: "Forge built-in MCP catalog",
    trust: "official",
    version: "2025.12.18",
    capabilities: ["mcp.tool", "reasoning"],
    risk: "safe",
    riskSummary: "Runs an official local MCP process; no external credentials required.",
    installInput: { kind: "mcp_catalog", catalogId: "modelcontextprotocol-sequential-thinking" },
    provenance: {
      type: "npm",
      packageName: "@modelcontextprotocol/server-sequential-thinking",
      packageVersion: "2025.12.18",
      repository: "https://github.com/modelcontextprotocol/servers/tree/main/src/sequentialthinking",
    },
    tags: ["official", "reasoning"],
    recommended: true,
  },
  {
    id: "mcp-catalog:modelcontextprotocol-github",
    kind: "mcp_server",
    name: "GitHub",
    title: "GitHub MCP",
    description: "Official MCP GitHub server for repositories, issues, pull requests, and code search.",
    source: "modelcontextprotocol-github",
    sourceLabel: "Forge built-in MCP catalog",
    trust: "official",
    version: "2025.4.8",
    capabilities: ["mcp.tool", "network.http", "github"],
    risk: "caution",
    riskSummary: "Requires a GitHub token before enabling; token-scoped GitHub operations still go through MCP permissions.",
    installInput: { kind: "mcp_catalog", catalogId: "modelcontextprotocol-github" },
    provenance: {
      type: "npm",
      packageName: "@modelcontextprotocol/server-github",
      packageVersion: "2025.4.8",
      repository: "https://github.com/modelcontextprotocol/servers/tree/main/src/github",
    },
    setupRequired: true,
    postInstall: "Configure GITHUB_PERSONAL_ACCESS_TOKEN in the MCP server settings before enabling.",
    tags: ["official", "github", "code"],
    recommended: true,
  },
  {
    id: "mcp-catalog:brave-search",
    kind: "mcp_server",
    name: "Brave Search",
    title: "Brave Search MCP",
    description: "Community MCP server for Brave Search results.",
    source: "brave-search",
    sourceLabel: "Forge built-in MCP catalog",
    trust: "curated",
    version: "0.6.2",
    capabilities: ["mcp.tool", "network.http", "web.search"],
    risk: "caution",
    riskSummary: "Requires BRAVE_API_KEY before enabling and uses external network search.",
    installInput: { kind: "mcp_catalog", catalogId: "brave-search" },
    provenance: {
      type: "npm",
      packageName: "@modelcontextprotocol/server-brave-search",
      packageVersion: "0.6.2",
      repository: "https://github.com/modelcontextprotocol/servers/tree/main/src/brave-search",
    },
    setupRequired: true,
    postInstall: "Configure BRAVE_API_KEY in MCP server settings before enabling.",
    tags: ["search", "web"],
  },
  {
    id: "mcp-catalog:modelcontextprotocol-puppeteer",
    kind: "mcp_server",
    name: "Puppeteer",
    title: "Puppeteer MCP",
    description: "MCP server for browser automation through Puppeteer.",
    source: "modelcontextprotocol-puppeteer",
    sourceLabel: "Forge built-in MCP catalog",
    trust: "curated",
    version: "2025.5.12",
    capabilities: ["mcp.tool", "runtime.browser", "process.exec"],
    risk: "caution",
    riskSummary: "Launches browser automation; Forge permissions and sandbox still gate tool calls.",
    installInput: { kind: "mcp_catalog", catalogId: "modelcontextprotocol-puppeteer" },
    provenance: {
      type: "npm",
      packageName: "@modelcontextprotocol/server-puppeteer",
      packageVersion: "2025.5.12",
      repository: "https://github.com/modelcontextprotocol/servers/tree/main/src/puppeteer",
    },
    tags: ["browser", "automation"],
  },
  {
    id: "mcp-catalog:modelcontextprotocol-postgres",
    kind: "mcp_server",
    name: "Postgres",
    title: "Postgres MCP",
    description: "MCP server for querying a Postgres database.",
    source: "modelcontextprotocol-postgres",
    sourceLabel: "Forge built-in MCP catalog",
    trust: "curated",
    version: "0.6.2",
    capabilities: ["mcp.tool", "database", "network.http"],
    risk: "caution",
    riskSummary: "Requires an explicit database connection string before enabling.",
    installInput: { kind: "mcp_catalog", catalogId: "modelcontextprotocol-postgres" },
    provenance: {
      type: "npm",
      packageName: "@modelcontextprotocol/server-postgres",
      packageVersion: "0.6.2",
      repository: "https://github.com/modelcontextprotocol/servers/tree/main/src/postgres",
    },
    setupRequired: true,
    postInstall: "Configure POSTGRES_CONNECTION_STRING before enabling.",
    tags: ["database", "postgres"],
  },
  ...[
    ["mcp-server-pdf", "PDF", "@modelcontextprotocol/server-pdf", "1.7.3", "PDF/document inspection workflows.", ["pdf", "documents"]],
    ["mcp-server-map", "Map", "@modelcontextprotocol/server-map", "1.7.3", "Map and geospatial workflows.", ["map", "geo"]],
    ["mcp-server-threejs", "Three.js", "@modelcontextprotocol/server-threejs", "1.7.3", "Three.js scene and 3D asset workflows.", ["threejs", "3d"]],
    ["mcp-server-blender", "Blender", "blender-mcp", "1.6.1", "Blender scene, material, camera, screenshot, and render workflows through Blender MCP.", ["blender", "3d", "rendering", "creative"]],
  ].map(([id, title, pkg, version, description, tags]) => ({
    id: `mcp-catalog:${id}`,
    kind: "mcp_server" as const,
    name: String(title),
    title: `${title} MCP`,
    description: String(description),
    source: String(id),
    sourceLabel: "Forge built-in MCP catalog",
    trust: "curated" as const,
    version: String(version),
    capabilities: ["mcp.tool", ...(tags as string[])],
    risk: "caution" as const,
    riskSummary: "Runs a curated local MCP package; tool calls still go through Forge permissions.",
    installInput: { kind: "mcp_catalog" as const, catalogId: String(id) },
    provenance: {
      type: "npm" as const,
      packageName: String(pkg),
      packageVersion: String(version),
      url: `https://www.npmjs.com/package/${encodeURIComponent(String(pkg)).replace("%40", "@").replace("%2F", "/")}`,
    },
    tags: tags as string[],
    ...(String(id) === "mcp-server-blender"
      ? {
        setupRequired: true,
        postInstall: "Install Blender 3.0+ and start the Blender MCP add-on/socket in Blender before using tools. ForgeAgent will run uvx blender-mcp and connect to localhost:9876.",
      }
      : {}),
  })),
  {
    id: "skill:serenity-invest-skill",
    kind: "skill",
    name: "serenity-invest-skill",
    title: "Serenity Invest Skill",
    description: "Supply-chain bottleneck investing skill for high-growth industry and A-share market analysis.",
    source: SERENITY_INVEST_SKILL_URL,
    sourceLabel: "Forge curated GitHub skill",
    trust: "curated",
    version: "latest",
    capabilities: ["skill", "investing", "research"],
    risk: "safe",
    riskSummary: "Readable skill package from GitHub. Scripts and data access still require explicit Forge tools and permissions.",
    installInput: { kind: "skill_github", url: SERENITY_INVEST_SKILL_URL, name: "serenity-invest-skill" },
    provenance: {
      type: "github",
      repository: SERENITY_INVEST_SKILL_URL,
    },
    tags: ["investing", "research", "a-share"],
    recommended: true,
  },
  {
    id: "skill:code-reviewer",
    kind: "skill",
    name: "code-reviewer",
    title: "Code Reviewer Skill",
    description: "Curated code review workflow skill from the public codex-skills repository.",
    source: CODE_REVIEWER_SKILL_URL,
    sourceLabel: "Forge curated GitHub skill",
    trust: "curated",
    version: "latest",
    capabilities: ["skill", "code-review"],
    risk: "safe",
    riskSummary: "Readable skill package from GitHub. Any scripts still run through Forge tools and permissions.",
    installInput: { kind: "skill_github", url: CODE_REVIEWER_SKILL_URL, name: "code-reviewer" },
    provenance: {
      type: "github",
      repository: "https://github.com/vadimcomanescu/codex-skills",
      url: CODE_REVIEWER_SKILL_URL,
    },
    tags: ["code", "review"],
    recommended: true,
  },
  {
    id: "skill:frontend-design",
    kind: "skill",
    name: "frontend-design",
    title: "Frontend Design Skill",
    description: "Curated frontend design skill for visual review and implementation guidance.",
    source: FRONTEND_DESIGN_SKILL_URL,
    sourceLabel: "Forge curated GitHub skill",
    trust: "curated",
    version: "latest",
    capabilities: ["skill", "frontend", "design"],
    risk: "safe",
    riskSummary: "Readable skill package from GitHub. Browser or file operations still go through Forge tools and permissions.",
    installInput: { kind: "skill_github", url: FRONTEND_DESIGN_SKILL_URL, name: "frontend-design" },
    provenance: {
      type: "github",
      repository: "https://github.com/vadimcomanescu/codex-skills",
      url: FRONTEND_DESIGN_SKILL_URL,
    },
    tags: ["frontend", "design"],
    recommended: true,
  },
  {
    id: "bundle:code-review-workspace",
    kind: "bundle",
    name: "code-review-workspace",
    title: "Code Review Workspace Bundle",
    description: "Installs the code-reviewer skill and Filesystem MCP for project code review.",
    source: "forge-builtin-bundle:code-review-workspace",
    sourceLabel: "Forge built-in bundle",
    trust: "curated",
    version: "1",
    capabilities: ["skill", "mcp_server", "fs.read", "fs.write", "code-review"],
    risk: "caution",
    riskSummary: "Expands into a curated GitHub skill plus Filesystem MCP; file operations remain sandboxed.",
    installInput: {
      kind: "bundle",
      name: "code-review-workspace",
      enable: true,
      items: [
        { kind: "skill_github", url: CODE_REVIEWER_SKILL_URL, name: "code-reviewer" },
        { kind: "mcp_catalog", catalogId: "modelcontextprotocol-filesystem", enable: true },
      ],
    },
    provenance: { type: "builtin" },
    tags: ["code-review", "workspace"],
    recommended: true,
  },
  {
    id: "bundle:design-reference",
    kind: "bundle",
    name: "design-reference",
    title: "Design Reference Bundle",
    description: "Installs the frontend-design skill and Everything MCP reference server.",
    source: "forge-builtin-bundle:design-reference",
    sourceLabel: "Forge built-in bundle",
    trust: "curated",
    version: "1",
    capabilities: ["skill", "mcp_server", "design", "mcp.resource.read"],
    risk: "caution",
    riskSummary: "Expands into a curated skill plus reference MCP; MCP launch remains permissioned.",
    installInput: {
      kind: "bundle",
      name: "design-reference",
      enable: true,
      items: [
        { kind: "skill_github", url: FRONTEND_DESIGN_SKILL_URL, name: "frontend-design" },
        { kind: "mcp_catalog", catalogId: "modelcontextprotocol-everything", enable: true },
      ],
    },
    provenance: { type: "builtin" },
    tags: ["frontend", "design"],
    recommended: true,
  },
  {
    id: "bundle:investor-research",
    kind: "bundle",
    name: "investor-research",
    title: "Investor Research Bundle",
    description: "Installs Serenity Invest and Sequential Thinking MCP for market research workflows.",
    source: "forge-builtin-bundle:investor-research",
    sourceLabel: "Forge built-in bundle",
    trust: "curated",
    version: "1",
    capabilities: ["skill", "mcp_server", "investing", "research"],
    risk: "caution",
    riskSummary: "Expands into a curated investing skill and local reasoning MCP. No trading actions are executed.",
    installInput: {
      kind: "bundle",
      name: "investor-research",
      enable: true,
      items: [
        { kind: "skill_github", url: SERENITY_INVEST_SKILL_URL, name: "serenity-invest-skill" },
        { kind: "mcp_catalog", catalogId: "modelcontextprotocol-sequential-thinking", enable: true },
      ],
    },
    provenance: { type: "builtin" },
    tags: ["investing", "research"],
    recommended: true,
  },
  {
    id: "bundle:pdf-research",
    kind: "bundle",
    name: "pdf-research",
    title: "PDF Research Bundle",
    description: "Installs PDF MCP and Filesystem MCP for local PDF research workflows.",
    source: "forge-builtin-bundle:pdf-research",
    sourceLabel: "Forge built-in bundle",
    trust: "curated",
    version: "1",
    capabilities: ["mcp_server", "pdf", "fs.read"],
    risk: "caution",
    riskSummary: "Expands into curated MCP packages. PDF/file access remains project-scoped and permissioned.",
    installInput: {
      kind: "bundle",
      name: "pdf-research",
      enable: true,
      items: [
        { kind: "mcp_catalog", catalogId: "mcp-server-pdf", enable: true },
        { kind: "mcp_catalog", catalogId: "modelcontextprotocol-filesystem", enable: true },
      ],
    },
    provenance: { type: "builtin" },
    tags: ["pdf", "research"],
    recommended: true,
  },
];
